"""Engine-neutral canonical domain primitives."""

from crypto_lab.domain.base import SCHEMA_VERSION, CanonicalModel
from crypto_lab.domain.canonical_json import canonical_json_bytes, canonical_json_text
from crypto_lab.domain.capability_names import CapabilityName, VocabularyVersion
from crypto_lab.domain.capability_requirements import (
    ApproximationPolicy,
    CapabilityRequirement,
)
from crypto_lab.domain.command_invocation import (
    CommandInvocationCheck,
    CommandInvocationRecord,
    CommandInvocationRuleViolation,
    ProcessIdentity,
    ProcessStartFacts,
    TimeoutBounds,
    assert_invocation_transition,
    assert_parent_run_eligibility,
    assert_write_once_enrichment,
    command_timeout_bounds,
)
from crypto_lab.domain.comparison_levels import ComparisonLevel
from crypto_lab.domain.compatibility import CompatibilityOutcome
from crypto_lab.domain.descriptors import (
    AdapterDescriptor,
    BoundedText,
    EngineDescriptor,
    OperatingSystem,
    RuntimeAvailabilityObservation,
    SupportedSchemaVersion,
)
from crypto_lab.domain.diagnostics import (
    Diagnostic,
    DiagnosticCategory,
    DiagnosticSeverity,
)
from crypto_lab.domain.experiment import (
    AdapterIdentity,
    BarOrderPriority,
    EngineIdentity,
    ExecutionAssumptions,
    ExperimentRecord,
    ExperimentSpec,
    ExperimentSpecDraft,
    FeeAssumptions,
    FillConvention,
    QueueFreezeCheck,
    QueueFreezeViolation,
    SelectedEngineSlot,
    SignalToOrderTiming,
    SlippageAssumptions,
    SlippageModel,
    SlotCompatibility,
    assert_queue_freeze,
    build_experiment_spec,
    experiment_configuration_hash,
    experiment_configuration_payload,
    experiment_spec_hash,
    experiment_spec_payload,
)
from crypto_lab.domain.financial import (
    CanonicalDecimal,
    NonNegativeDecimal,
    PositiveDecimal,
    format_decimal,
)
from crypto_lab.domain.hashing import (
    CanonicalHashEnvelope,
    HashingProfile,
    attempt_token_hash,
    profile_hash,
    sha256_bytes,
)
from crypto_lab.domain.identifiers import (
    ArtifactId,
    AssetCode,
    AttemptToken,
    AuditEventId,
    CandidateArtifactId,
    CorrelationId,
    DatasetId,
    DatasetPartitionId,
    DiagnosticId,
    EventId,
    ExperimentId,
    InvocationId,
    LogicalSlotId,
    NormalizedIdentifier,
    RunId,
    Sha256,
    StrategyId,
    StrategyVersionId,
)
from crypto_lab.domain.lifecycle import (
    COMMAND_INVOCATION_TRANSITIONS,
    ENGINE_RUN_TRANSITIONS,
    EXPERIMENT_TRANSITIONS,
    RECOGNIZED_NATIVE_EXIT_VALUES,
    TERMINAL_COMMAND_INVOCATION_STATES,
    TERMINAL_ENGINE_RUN_STATES,
    TERMINAL_EXPERIMENT_STATES,
    CommandInvocationState,
    CommandKind,
    EngineRunState,
    ExperimentState,
    ProcessExitCategory,
    RetryTerminalState,
    TransitionTable,
    is_allowed_transition,
    permitted_successors,
    process_exit_category_for,
)
from crypto_lab.domain.ports import Clock, IdentitySource
from crypto_lab.domain.records import (
    InstrumentId,
    InstrumentRef,
    MarketType,
    Money,
    Price,
    Quantity,
)
from crypto_lab.domain.results import Failure, Result, Success
from crypto_lab.domain.retry import RetryPolicy
from crypto_lab.domain.time import UtcDateTime, format_utc
from crypto_lab.domain.versioning import SemanticVersion, parse_semantic_version

__all__ = (
    "COMMAND_INVOCATION_TRANSITIONS",
    "ENGINE_RUN_TRANSITIONS",
    "EXPERIMENT_TRANSITIONS",
    "RECOGNIZED_NATIVE_EXIT_VALUES",
    "SCHEMA_VERSION",
    "TERMINAL_COMMAND_INVOCATION_STATES",
    "TERMINAL_ENGINE_RUN_STATES",
    "TERMINAL_EXPERIMENT_STATES",
    "AdapterDescriptor",
    "AdapterIdentity",
    "ApproximationPolicy",
    "ArtifactId",
    "AssetCode",
    "AttemptToken",
    "AuditEventId",
    "BarOrderPriority",
    "BoundedText",
    "CandidateArtifactId",
    "CanonicalDecimal",
    "CanonicalHashEnvelope",
    "CanonicalModel",
    "CapabilityName",
    "CapabilityRequirement",
    "Clock",
    "CommandInvocationCheck",
    "CommandInvocationRecord",
    "CommandInvocationRuleViolation",
    "CommandInvocationState",
    "CommandKind",
    "ComparisonLevel",
    "CompatibilityOutcome",
    "CorrelationId",
    "DatasetId",
    "DatasetPartitionId",
    "Diagnostic",
    "DiagnosticCategory",
    "DiagnosticId",
    "DiagnosticSeverity",
    "EngineDescriptor",
    "EngineIdentity",
    "EngineRunState",
    "EventId",
    "ExecutionAssumptions",
    "ExperimentId",
    "ExperimentRecord",
    "ExperimentSpec",
    "ExperimentSpecDraft",
    "ExperimentState",
    "Failure",
    "FeeAssumptions",
    "FillConvention",
    "HashingProfile",
    "IdentitySource",
    "InstrumentId",
    "InstrumentRef",
    "InvocationId",
    "LogicalSlotId",
    "MarketType",
    "Money",
    "NonNegativeDecimal",
    "NormalizedIdentifier",
    "OperatingSystem",
    "PositiveDecimal",
    "Price",
    "ProcessExitCategory",
    "ProcessIdentity",
    "ProcessStartFacts",
    "Quantity",
    "QueueFreezeCheck",
    "QueueFreezeViolation",
    "Result",
    "RetryPolicy",
    "RetryTerminalState",
    "RunId",
    "RuntimeAvailabilityObservation",
    "SelectedEngineSlot",
    "SemanticVersion",
    "Sha256",
    "SignalToOrderTiming",
    "SlippageAssumptions",
    "SlippageModel",
    "SlotCompatibility",
    "StrategyId",
    "StrategyVersionId",
    "Success",
    "SupportedSchemaVersion",
    "TimeoutBounds",
    "TransitionTable",
    "UtcDateTime",
    "VocabularyVersion",
    "assert_invocation_transition",
    "assert_parent_run_eligibility",
    "assert_queue_freeze",
    "assert_write_once_enrichment",
    "attempt_token_hash",
    "build_experiment_spec",
    "canonical_json_bytes",
    "canonical_json_text",
    "command_timeout_bounds",
    "experiment_configuration_hash",
    "experiment_configuration_payload",
    "experiment_spec_hash",
    "experiment_spec_payload",
    "format_decimal",
    "format_utc",
    "is_allowed_transition",
    "parse_semantic_version",
    "permitted_successors",
    "process_exit_category_for",
    "profile_hash",
    "sha256_bytes",
)
